import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";  
import HeaderText from "@/components/layout/header-text";  


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[linear-gradient(90deg,rgba(2,0,1,0.993)_0%,rgb(2,6,48)_100%)]`}
      >
        <div className="py-[2px] px-[4%]">
          <Navbar/>
          <HeaderText/>
          
          {children}
        </div>
      </body>
    </html>
  );
}
